# Generated by Django 5.0.3 on 2024-04-27 15:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animelist", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="animewatchlater",
            name="user",
        ),
        migrations.RemoveField(
            model_name="liked",
            name="user",
        ),
        migrations.RemoveField(
            model_name="mangawatchlater",
            name="user",
        ),
        migrations.AddField(
            model_name="animewatchlater",
            name="user",
            field=models.ManyToManyField(
                related_name="later_anime", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="liked",
            name="user",
            field=models.ManyToManyField(
                related_name="liked", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="mangawatchlater",
            name="user",
            field=models.ManyToManyField(
                related_name="later_manga", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
