# Generated by Django 5.0.3 on 2024-04-26 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_pic",
            field=models.ImageField(
                blank=True,
                default="/userprofile/static/icons/user.png",
                null=True,
                upload_to="",
            ),
        ),
    ]
