# Generated by Django 5.0.3 on 2024-04-26 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0002_alter_user_profile_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_pic",
            field=models.ImageField(
                blank=True, default="/icons/user.png", null=True, upload_to=""
            ),
        ),
    ]
