# Generated by Django 5.0.3 on 2024-04-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0003_alter_user_profile_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_name",
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
